# Generated by Django 2.2.1 on 2019-05-27 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190525_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 27, 18, 20, 56, 735203)),
        ),
    ]
